import mongoose from "mongoose";

const matchSchema = new mongoose.Schema({
  match_id: { type: Number },
  title: { type: String },
  short_title: { type: String },
  subtitle: { type: String },
  match_number: { type: String },
  format: { type: Number },
  format_str: { type: String },
  status: { type: String },
  status_str: { type: String },
  status_note: { type: String },
  verified: { type: Boolean },
  pre_squad: { type: Boolean },
  odds_available: { type: Boolean },
  game_state: { type: Number },
  game_state_str: { type: String },
  domestic: { type: Boolean },
  competition: {
    cid: { type: Number },
    title: { type: String },
    abbr: { type: String },
    type: { type: String },
    category: { type: String },
    match_format: { type: String },
    season: { type: String },
    status: { type: String },
    datestart: { type: Date },
    dateend: { type: Date },
    country: { type: String },
    total_matches: { type: Number },
    total_rounds: { type: Number },
    total_teams: { type: Number },
  },
  teama: {
    team_id: { type: Number },
    name: { type: String },
    short_name: { type: String },
    logo_url: { type: String },
    scores_full: { type: String },
    scores: { type: String },
    overs: { type: String },
  },
  teamb: {
    team_id: { type: Number },
    name: { type: String },
    short_name: { type: String },
    logo_url: { type: String },
    scores_full: { type: String },
    scores: { type: String },
    overs: { type: String },
  },
  date_start: { type: Date },
  date_end: { type: Date },
  timestamp_start: { type: Number },
  timestamp_end: { type: Number },
  date_start_ist: { type: Date },
  date_end_ist: { type: Date },
  venue: {
    venue_id: { type: String },
    name: { type: String },
    location: { type: String },
    country: { type: String },
    timezone: { type: String },
  },
  umpires: { type: String },
  referee: { type: String },
  equation: { type: String },
  live: { type: String },
  result: { type: String },
  result_type: { type: Number },
  win_margin: { type: String },
  winning_team_id: { type: Number },
  commentary: { type: Number },
  wagon: { type: Number },
  latest_inning_number: { type: Number },
  presquad_time: { type: Date },
  verify_time: { type: Date },
  match_dls_affected: { type: Boolean },
  toss: {
    text: { type: String },
    winner: { type: Number },
    decision: { type: Number },
  },
});

const Match = mongoose.model("Match", matchSchema);

export default Match;
